// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: detect.proto

package Detect

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoxRect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X       float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`                           // x 坐标
	Y       float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`                           // y 坐标
	Width   float64 `protobuf:"fixed64,3,opt,name=width,proto3" json:"width,omitempty"`                   // 宽度
	Height  float64 `protobuf:"fixed64,4,opt,name=height,proto3" json:"height,omitempty"`                 // 高度
	Area    float64 `protobuf:"fixed64,5,opt,name=area,proto3" json:"area,omitempty"`                     // 面积
	ClassId int64   `protobuf:"varint,6,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"` // 检测种类
}

func (x *BoxRect) Reset() {
	*x = BoxRect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BoxRect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoxRect) ProtoMessage() {}

func (x *BoxRect) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoxRect.ProtoReflect.Descriptor instead.
func (*BoxRect) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{0}
}

func (x *BoxRect) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoxRect) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoxRect) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoxRect) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BoxRect) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

func (x *BoxRect) GetClassId() int64 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

type DetectRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *DetectRequest) Reset() {
	*x = DetectRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectRequest) ProtoMessage() {}

func (x *DetectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectRequest.ProtoReflect.Descriptor instead.
func (*DetectRequest) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{1}
}

func (x *DetectRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type DetectResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Rect   []*BoxRect `protobuf:"bytes,2,rep,name=rect,proto3" json:"rect,omitempty"`
	Image  []byte     `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
}

func (x *DetectResponse) Reset() {
	*x = DetectResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_detect_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DetectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectResponse) ProtoMessage() {}

func (x *DetectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_detect_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetectResponse.ProtoReflect.Descriptor instead.
func (*DetectResponse) Descriptor() ([]byte, []int) {
	return file_detect_proto_rawDescGZIP(), []int{2}
}

func (x *DetectResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *DetectResponse) GetRect() []*BoxRect {
	if x != nil {
		return x.Rect
	}
	return nil
}

func (x *DetectResponse) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_detect_proto protoreflect.FileDescriptor

var file_detect_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x22, 0x82, 0x01, 0x0a, 0x07, 0x42, 0x6f, 0x78, 0x52, 0x65,
	0x63, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78,
	0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x77,
	0x69, 0x64, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x61, 0x72, 0x65, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61,
	0x12, 0x19, 0x0a, 0x08, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0d, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x63, 0x0a, 0x0e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23,
	0x0a, 0x04, 0x72, 0x65, 0x63, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x44,
	0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x42, 0x6f, 0x78, 0x52, 0x65, 0x63, 0x74, 0x52, 0x04, 0x72,
	0x65, 0x63, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x32, 0x56, 0x0a, 0x13, 0x44, 0x65, 0x74,
	0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x3f, 0x0a, 0x0c, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x65, 0x64, 0x52, 0x65, 0x63, 0x74,
	0x12, 0x15, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74,
	0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x18, 0x5a, 0x16, 0x2f, 0x64, 0x65, 0x74, 0x65, 0x63, 0x74, 0x5f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x3b, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_detect_proto_rawDescOnce sync.Once
	file_detect_proto_rawDescData = file_detect_proto_rawDesc
)

func file_detect_proto_rawDescGZIP() []byte {
	file_detect_proto_rawDescOnce.Do(func() {
		file_detect_proto_rawDescData = protoimpl.X.CompressGZIP(file_detect_proto_rawDescData)
	})
	return file_detect_proto_rawDescData
}

var file_detect_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_detect_proto_goTypes = []interface{}{
	(*BoxRect)(nil),        // 0: Detect.BoxRect
	(*DetectRequest)(nil),  // 1: Detect.DetectRequest
	(*DetectResponse)(nil), // 2: Detect.DetectResponse
}
var file_detect_proto_depIdxs = []int32{
	0, // 0: Detect.DetectResponse.rect:type_name -> Detect.BoxRect
	1, // 1: Detect.DetectResultService.DetectedRect:input_type -> Detect.DetectRequest
	2, // 2: Detect.DetectResultService.DetectedRect:output_type -> Detect.DetectResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_detect_proto_init() }
func file_detect_proto_init() {
	if File_detect_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_detect_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BoxRect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_detect_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DetectResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_detect_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_detect_proto_goTypes,
		DependencyIndexes: file_detect_proto_depIdxs,
		MessageInfos:      file_detect_proto_msgTypes,
	}.Build()
	File_detect_proto = out.File
	file_detect_proto_rawDesc = nil
	file_detect_proto_goTypes = nil
	file_detect_proto_depIdxs = nil
}
