// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: detect.proto
#ifndef GRPC_detect_2eproto__INCLUDED
#define GRPC_detect_2eproto__INCLUDED

#include "detect.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace Detect {

class DetectResultService final {
 public:
  static constexpr char const* service_full_name() {
    return "Detect.DetectResultService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status DetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::Detect::DetectResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Detect::DetectResponse>> AsyncDetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Detect::DetectResponse>>(AsyncDetectedRectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Detect::DetectResponse>> PrepareAsyncDetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::Detect::DetectResponse>>(PrepareAsyncDetectedRectRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void DetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest* request, ::Detect::DetectResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void DetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest* request, ::Detect::DetectResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Detect::DetectResponse>* AsyncDetectedRectRaw(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::Detect::DetectResponse>* PrepareAsyncDetectedRectRaw(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status DetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::Detect::DetectResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Detect::DetectResponse>> AsyncDetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Detect::DetectResponse>>(AsyncDetectedRectRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Detect::DetectResponse>> PrepareAsyncDetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::Detect::DetectResponse>>(PrepareAsyncDetectedRectRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void DetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest* request, ::Detect::DetectResponse* response, std::function<void(::grpc::Status)>) override;
      void DetectedRect(::grpc::ClientContext* context, const ::Detect::DetectRequest* request, ::Detect::DetectResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::Detect::DetectResponse>* AsyncDetectedRectRaw(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::Detect::DetectResponse>* PrepareAsyncDetectedRectRaw(::grpc::ClientContext* context, const ::Detect::DetectRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_DetectedRect_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status DetectedRect(::grpc::ServerContext* context, const ::Detect::DetectRequest* request, ::Detect::DetectResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_DetectedRect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_DetectedRect() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_DetectedRect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectedRect(::grpc::ServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectedRect(::grpc::ServerContext* context, ::Detect::DetectRequest* request, ::grpc::ServerAsyncResponseWriter< ::Detect::DetectResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_DetectedRect<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_DetectedRect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_DetectedRect() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::Detect::DetectRequest, ::Detect::DetectResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::Detect::DetectRequest* request, ::Detect::DetectResponse* response) { return this->DetectedRect(context, request, response); }));}
    void SetMessageAllocatorFor_DetectedRect(
        ::grpc::MessageAllocator< ::Detect::DetectRequest, ::Detect::DetectResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::Detect::DetectRequest, ::Detect::DetectResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_DetectedRect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectedRect(::grpc::ServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DetectedRect(
      ::grpc::CallbackServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_DetectedRect<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_DetectedRect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_DetectedRect() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_DetectedRect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectedRect(::grpc::ServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_DetectedRect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_DetectedRect() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_DetectedRect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectedRect(::grpc::ServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDetectedRect(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_DetectedRect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_DetectedRect() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->DetectedRect(context, request, response); }));
    }
    ~WithRawCallbackMethod_DetectedRect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status DetectedRect(::grpc::ServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* DetectedRect(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_DetectedRect : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_DetectedRect() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::Detect::DetectRequest, ::Detect::DetectResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::Detect::DetectRequest, ::Detect::DetectResponse>* streamer) {
                       return this->StreamedDetectedRect(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_DetectedRect() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status DetectedRect(::grpc::ServerContext* /*context*/, const ::Detect::DetectRequest* /*request*/, ::Detect::DetectResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDetectedRect(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::Detect::DetectRequest,::Detect::DetectResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_DetectedRect<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_DetectedRect<Service > StreamedService;
};

}  // namespace Detect


#endif  // GRPC_detect_2eproto__INCLUDED
